# array_1d: 一维数组
# 期望输出:
#   len = 4
#   [0] = 10
#   after set: 10 99 30
#   sum = 179
def main() -> () {
	a:int = [10, 20, 30, 40]  # = 等价于 <-
	len(a) -> n
	print("len =", n)
	v0 <- a[0]
	print("[0] =", v0)
	a[1] <- 99
	x0 = a[0]  # = 等价于 <-
	a[1] -> x1
	x2 <- a[2]
	print("after set:", x0, x1, x2)
	total = 0  # = 等价于 <-
	0 -> i
	while (i < n) {
		x <- a[i]
		total = total + x  # = 等价于 <-
		i + 1 -> i
	}
	print("sum =", total)
}

main()
