# 期望输出:
#   add(10,20) = 30
#   double(add(10,20)) = 60

# 02-func: defining and calling functions
# Run: kvlang tutorial/04-func/

def add(A: int, B: int) -> (C: int) {
    A + B -> C
}

def double(x: int) -> (y: int) {
    x * 2 -> y
}

def main() -> () {
    add(10, 20) -> a           // 30
    print("add(10,20) =", a)

    double(a) -> b             // 60
    print("double(add(10,20)) =", b)
}

main() -> ()
