# 007: Reverse Integer
# 来源: LeetCode #7
# 期望输出:
#   321
#   -321
def reverse(x:int) -> (result:int) {
	neg = x < 0  # = 等价于 <-
	x -> n

	if (neg) {
		n <- -x
	}

	rev = 0  # = 等价于 <-
	while (n > 0) {
		rev * 10 -> r
		d <- n % 10
		rev = r + d  # = 等价于 <-
		n / 10 -> n
	}

	if (neg) {
		result <- -rev
	} else {
		result = rev  # = 等价于 <-
	}
}

reverse(123) -> r1
print(r1)
r2 <- reverse(-123)
print(r2)
