# 035 Search Insert Position
# 期望输出: 2, 1, 4
def searchInsert(nums, target:int) -> (pos:int) {
    0 -> pos
    len(nums) -> n
    while (pos < n) {
        at(nums, pos) -> v
        v >= target -> found
        if (found) {
            pos -> pos
        }
        pos + 1 -> pos
    }
}

array(1, 3, 5, 6) -> nums1
searchInsert(nums1, 5) -> a
print("ins 5 =", a)
searchInsert(nums1, 2) -> b
print("ins 2 =", b)
searchInsert(nums1, 7) -> c
print("ins 7 =", c)
a -> /search_5
