// 011: Container With Most Water — 数组参数版
// 来源: LeetCode #11
// 期望输出:
//   49
rwfunc max_area(h:[]int64) -> (mx:int64) {
	ndarray·numel(h) -> n
	l = 0
	r = n - 1
	0 -> mx
	while (l < r) {
		hl = h[l]
		hr = h[r]
		r - l -> w
		ls = hl < hr

		if (ls) {
			ar = hl × w
			ar_m = hl × w
			l + 1 -> l
		} else {
			ar = hr × w
			ar_m = hr × w
			r = r - 1
		}

		ar > mx -> bg

		if (bg) {
			mx = ar
		}
	}
}

rwfunc test() -> () {

	a:[]int64 = [1, 8, 6, 2, 5, 4, 8, 3, 7]
	r = max_area(a)
	println(r)
}
