// 013 Roman to Integer
// 期望输出: 58, 1994
rwfunc romanToInt(s:[]char/utf32) -> (val:int64) {
	0 -> val
	i = 0
	n = string·len(s)
	"" -> prev
	while (i < n) {
		c = s[i]
		isI = c == "I"
		c == "V" -> isV
		isX = c == "X"
		isL = c == "L"
		c == "C" -> isC
		isD = c == "D"
		isM = c == "M"
		pI = prev == "I"
		prev == "X" -> pX
		pC = prev == "C"

		if (isI) {
			val = val + 1
		}

		if (isV) {
			val + 5 -> val
		}

		if (isX) {
			val = val + 10
		}

		if (isL) {
			val = val + 50
		}

		if (isC) {
			val + 100 -> val
		}

		if (isD) {
			val = val + 500
		}

		if (isM) {
			val + 1000 -> val
		}

		subI = pI
		pX -> subX
		subC = pC

		if (isV) {
			if (subI) {
				val = val - 2
			}
		}

		if (isX) {
			if (subI) {
				val - 2 -> val
			}
		}

		if (isL) {
			if (subX) {
				val = val - 20
			}
		}

		if (isC) {
			if (subX) {
				val = val - 20
			}
		}

		if (isD) {
			if (subC) {
				val - 200 -> val
			}
		}

		if (isM) {
			if (subC) {
				val = val - 200
			}
		}

		prev = c
		i = i + 1
	}
}

rwfunc test() -> () {

	romanToInt("LVIII") -> a
	println("LVIII =", a)
	b = romanToInt("MCMXCIV")
	println("MCMXCIV =", b)
	/roman_lviii = a
}
