# 013 Roman to Integer
# 期望输出: 58, 1994
rwfunc romanToInt(s:[]char/utf32) -> (val:int64) {
	0 -> val
	i <- 0
	n = string·len(s)  # = 等价于 <-
	"" -> prev
	while (i < n) {
		c <- s[i]
		isI = c == "I"  # = 等价于 <-
		c == "V" -> isV
		isX <- c == "X"
		isL = c == "L"  # = 等价于 <-
		c == "C" -> isC
		isD <- c == "D"
		isM = c == "M"  # = 等价于 <-
		pI = prev == "I"  # = 等价于 <-
		prev == "X" -> pX
		pC <- prev == "C"

		if (isI) {
			val = val + 1  # = 等价于 <-
		}

		if (isV) {
			val + 5 -> val
		}

		if (isX) {
			val <- val + 10
		}

		if (isL) {
			val = val + 50  # = 等价于 <-
		}

		if (isC) {
			val + 100 -> val
		}

		if (isD) {
			val <- val + 500
		}

		if (isM) {
			val + 1000 -> val
		}

		subI = pI  # = 等价于 <-
		pX -> subX
		subC <- pC

		if (isV) {
			if (subI) {
				val = val - 2  # = 等价于 <-
			}
		}

		if (isX) {
			if (subI) {
				val - 2 -> val
			}
		}

		if (isL) {
			if (subX) {
				val <- val - 20
			}
		}

		if (isC) {
			if (subX) {
				val = val - 20  # = 等价于 <-
			}
		}

		if (isD) {
			if (subC) {
				val - 200 -> val
			}
		}

		if (isM) {
			if (subC) {
				val <- val - 200
			}
		}

		prev <- c
		i = i + 1  # = 等价于 <-
	}
}

rwfunc test() -> () {

	romanToInt("LVIII") -> a
	println("LVIII =", a)
	b <- romanToInt("MCMXCIV")
	println("MCMXCIV =", b)
	/roman_lviii = a  # = 等价于 <-
}
