// 038: Count and Say — 报数序列
// 来源: LeetCode #38
// 存储：(val, count) 交替排列在数组中
// 期望输出:
//   1
//   11
//   21
//   1211
//   111221
rwfunc next_seq(src_len:int64) -> (dst_len:int64) {
	/tmp/s2:[int64]·int64 = {}
	i = 0
	di = 0
	while (i < src_len) {
		kvspace·get("/tmp/s", i) -> cur
		count = 1
		j = i + 1
		while (j < src_len) {
			kvspace·get("/tmp/s", j) -> v
			if (v == cur) { count + 1 -> count ; j + 1 -> j }
			else { src_len -> j }
		}
			_ = kvspace·set("/tmp/s2", di, count)
			_ = kvspace·set("/tmp/s2", di+1, cur)
		di + 2 -> di
		i + count -> i
	}
	di -> dst_len
}

rwfunc print_seq_len(seq_len:int64) -> () {
	i = 0
	while (i < seq_len) {
		kvspace·get("/tmp/s", i) -> cnt
		kvspace·get("/tmp/s", i+1) -> val
		k = 0
		while (k < cnt) {
			print(val)
			k + 1 -> k
		}
		i + 2 -> i
	}
	println()
}

rwfunc copy_from_s2_to_s(s2_len:int64) -> () {
	i = 0
	while (i < s2_len) {
		/tmp/s2[i] -> v
		_ = kvspace·set("/tmp/s", i, v)
		i + 1 -> i
	}
}

rwfunc count_and_say(N:int64) -> () {
	/tmp/s:[int64]·int64 = {}
	_ = kvspace·set("/tmp/s", 0, 1)   // count=1 of digit 1
	_ = kvspace·set("/tmp/s", 1, 1)
	cur_len = 2
	round = 1
	while (round < N) {
		l = next_seq(cur_len)
		copy_from_s2_to_s(l)
		l -> cur_len
		round + 1 -> round
	}
	print_seq_len(cur_len)
}

rwfunc test() -> () {
	count_and_say(1)
	count_and_say(2)
	count_and_say(3)
	count_and_say(4)
	count_and_say(5)
}
