// 053: Maximum Subarray — Kadane 算法
// 算法: 动态规划 O(n)，cur = max(x, cur+x)
// 来源: LeetCode #53
// 期望输出:
//   6
rwfunc max_subarray(nums:[]int64) -> () {
	a:[]int64 = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
	n = ndarray·numel(a)
	a[0] -> cur
	max = a[0]
	i = 1
	while (i < n) {
		a[i] -> x
		curx = cur + x
		take_x = x > curx

		if (take_x) {
			x -> cur
		} else {
			cur = curx
		}

		bigger = cur > max

		if (bigger) {
			cur -> max
		}

		i = i + 1
	}
	println(max)
}

rwfunc test() -> () {

	nums:[]int64 = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
	max_subarray(nums)
}
