// 062: Unique Paths — DP 机器人路径数
// 来源: LeetCode #62
// 期望输出:
//   28
//   3
rwfunc dp(m:int64, n:int64) -> (result:int64) {
	/tmp/up:[int64]·int64 = {}
	i = 0
	while (i < n) {
		_ = kvspace·set("/tmp/up", i, 1)
		i + 1 -> i
	}
	j = 1
	while (j < m) {
		k = 1
		while (k < n) {
			kvspace·get("/tmp/up", k) -> v
			kvspace·get("/tmp/up", k-1) -> prev
			_ = kvspace·set("/tmp/up", k, prev + v)
			k + 1 -> k
		}
		j + 1 -> j
	}
	kvspace·get("/tmp/up", n-1) -> result
}

rwfunc test() -> () {
	r1 = dp(3, 7)
	println(r1)
	r2 = dp(3, 2)
	println(r2)
}
