// 100: Same Tree — 判断两棵二叉树是否相同
// 来源: LeetCode #100
// 期望输出:
//   true
//   false
struct TNode {
	val:int64=0
	left:*TNode=None
	right:*TNode=None
}

rwfunc same(a:TNode, b:TNode) -> (ok:int64) {
	if (a == None || b == None) {
		if (a == b) { 1 -> ok } else { 0 -> ok }
	} else {
		if (a·val == b·val) {
			same(a·left, b·left) -> ok
			if (ok == 1) {
				same(a·right, b·right) -> ok
			}
		} else { 0 -> ok }
	}
}

rwfunc test() -> () {
	t:[int64]·TNode = {}
	t·2:TNode = {val=2}
	t·3:TNode = {val=3}
	t·1:TNode = {val=1 left=&t·2 right=&t·3}
	&t·1 -> rt

	v:[int64]·TNode = {}
	v·2:TNode = {val=2}
	v·3:TNode = {val=4}
	v·1:TNode = {val=1 left=&v·2 right=&v·3}
	&v·1 -> rv

	same(rt, rt) -> r1
	if (r1 == 1) { println("true") } else { println("false") }
	same(rt, rv) -> r2
	if (r2 == 1) { println("true") } else { println("false") }
}
