// 104: Maximum Depth of Binary Tree — 二叉树最大深度
// 来源: LeetCode #104
// 期望输出:
//   3
rwfunc build_tree() -> () {
	/t0 = { val=3; left="/t1"; right="/t2" }
	{ val=9; left=""; right="" } -> /t1
	/t2 <- { val=20; left="/t3"; right="/t4" }
	/t3 = { val=15; left=""; right="" }  // = 等价于 <-
	{ val=7; left=""; right="" } -> /t4
}

rwfunc max_depth(root:[]char/utf32) -> (depth:int64) {
	if (root == "") { 0 -> depth }
	else {
		ld = max_depth(root·left)  // = 等价于 <-
		rd <- max_depth(root·right)
		if (ld > rd) { ld + 1 -> depth }
		else { depth <- rd + 1 }
	}
}

rwfunc test() -> () {
	build_tree()
	d <- max_depth("/t0")
	println(d)
}
