// 141: Linked List Cycle — 快慢指针
// 来源: LeetCode #141
// 期望输出:
//   1
//   0
rwfunc has_cycle(head:Node) -> (result:int64) {
	result = 0
	head -> slow
	fast = head
	while (fast != None) {
		slow = slow·next
		fast·next -> n1
		at_end = n1 == None

		if (at_end) {
			fast = None
		} else {
			n1·next -> fast
			match = slow == fast

			if (match) {
				result = 1
				None -> fast
			}
		}
	}
}

struct Node {
	val:int64=0
	next:*Node=None
}

rwfunc test() -> () {
	c1:Node = {val=3}
	c2:Node = {val=2}
	c3:Node = {val=0}
	c1·next = &c2
	c2·next = &c3
	c3·next = &c1
	&c1 -> h1
	r1 = has_cycle(h1)
	println(r1)

	d2:Node = {val=2}
	d1:Node = {val=1 next=&d2}
	&d1 -> h2
	has_cycle(h2) -> r2
	println(r2)
}
