// 141: Linked List Cycle — 快慢指针
// 来源: LeetCode #141
// 期望输出:
//   1
//   0
rwfunc has_cycle(head:[]char/utf32) -> (result:int64) {
	result = 0
	head -> slow
	fast = head
	while (fast != "") {
		slow = slow·next
		fast·next -> n1
		at_end = n1 == ""

		if (at_end) {
			fast = ""
		} else {
			n1·next -> fast
			match = slow == fast

			if (match) {
				result = 1
				"" -> fast
			}
		}
	}
}

struct Node {
	val:int64=0
	next:[]char/utf32=""
}

rwfunc test() -> () {
	c:[int64]·/lib/Node = {}
	kv·abs(c) -> cb
	cb + "·1" -> c1
	cb + "·2" -> c2
	cb + "·3" -> c3
	Node{val=3 next=c2} -> c·1
	Node{val=2 next=c3} -> c·2
	Node{val=0 next=c1} -> c·3
	r1 = has_cycle(c1)
	println(r1)

	n:[int64]·/lib/Node = {}
	kv·abs(n) -> nb
	nb + "·1" -> n1
	nb + "·2" -> n2
	Node{val=1 next=n2} -> n·1
	Node{val=2 next=""} -> n·2
	has_cycle(n1) -> r2
	println(r2)
}
