// 203: Remove Linked List Elements
// 来源: LeetCode #203
// 期望输出:
//   1
//   2
//   3
//   4
//   5
struct Node {
	val:int64=0
	next:*Node=None
}

rwfunc remove(head:Node, val:int64) -> () {
	head -> p
	while (p != None) {
		v = p·val
		v == val -> skip

		if (skip) {
		} else {
			println(v)
		}

		p = p·next
	}
}

rwfunc test() -> () {
	n7:Node = {val=6}
	n6:Node = {val=5 next=&n7}
	n5:Node = {val=4 next=&n6}
	n4:Node = {val=3 next=&n5}
	n3:Node = {val=6 next=&n4}
	n2:Node = {val=2 next=&n3}
	n1:Node = {val=1 next=&n2}
	&n1 -> h
	remove(h, 6)
}
