// 206: Reverse Linked List
// 来源: LeetCode #206
// 期望输出:
//   5
//   4
//   3
//   2
//   1
struct Node {
	val:int64=0
	next:*Node=""
}

rwfunc reverse(head:*Node) -> () {
	prev = ""
	head -> cur
	while (cur != "") {
		nxt = cur·next
		cur·next = prev
		cur -> prev
		cur = nxt
	}
	p = prev
	while (p != "") {
		p·val -> v
		println(v)
		p = p·next
	}
}

rwfunc test() -> () {
	n5:Node = {val=5}
	n4:Node = {val=4 next=&n5}
	n3:Node = {val=3 next=&n4}
	n2:Node = {val=2 next=&n3}
	n1:Node = {val=1 next=&n2}
	&n1 -> h
	reverse(h)
}
