// collatz: Collatz 猜想步数
// 算法: while + 条件分支，start=27
// 期望输出:
//   steps = 111
rwfunc collatz(n:int64) -> (steps:int64) {
	n -> nv
	0 -> steps
	while (nv > 1) {
		mod = nv % 2
		even = mod == 0

		if (even) {
			nv ÷ 2 -> nv
			nv ÷ 2 -> nv_m
		} else {
			t = nv × 3
			t_m = nv × 3
			nv = t + 1
		}

		steps + 1 -> steps
	}
}

rwfunc test() -> () {

	ans = collatz(27)
	println("steps =", ans)
	/last_steps = ans
}
