# fibonacci: 迭代斐波那契数列
# 算法: while 循环 + 临时交换，计算 fib(10) = 55
# 期望输出:
#   fib = 55
rwfunc fibonacci(n:int64) -> (result:int64) {
	if (n <= 1) {
		n -> result
	} else {
		a <- 0
		b = 1  # = 等价于 <-
		2 -> i
		while (i <= n) {
			c <- a + b
			a = b  # = 等价于 <-
			c -> b
			i <- i + 1
		}
		result = b  # = 等价于 <-
	}
}

rwfunc test() -> () {

	t0 <- time·now()
	fibonacci(10) -> ans
	t1 <- time·now()
	println("fib =", ans)
	delta <- time·sub(t1, t0)
	ns <- time/duration·as_nanos(delta)
	println("__bench_ns:", ns)
}
