# 期望输出:
#   add: 13
#   sub: 7
#   mul: 30
#   div: 3
#   pow: 32.0
#   sqrt: 12.0
rwfunc main() -> () {
	10 + 3 -> add_r
	println("add:", add_r)
	sub_r <- 10 - 3
	println("sub:", sub_r)
	mul_r = 10 * 3  # = 等价于 <-
	println("mul:", mul_r)
	10 / 3 -> div_r
	println("div:", div_r)
	pow_r <- pow(2, 5)
	println("pow:", pow_r)
	sqrt_r = sqrt(144)  # = 等价于 <-
	println("sqrt:", sqrt_r)
	0 -> /ops_count
	/ops_count <- /ops_count + 6
}

main()
