# 011: Container With Most Water — 数组参数版
# 来源: LeetCode #11
# 期望输出:
#   49
def max_area(h:int64) -> (mx:int64) {
	len(h) -> n
	l <- 0
	r = n - 1  # = 等价于 <-
	0 -> mx
	while (l < r) {
		hl <- h[l]
		hr = h[r]  # = 等价于 <-
		r - l -> w
		ls <- hl < hr

		if (ls) {
			ar = hl * w  # = 等价于 <-
			l + 1 -> l
		} else {
			ar <- hr * w
			r = r - 1  # = 等价于 <-
		}

		ar > mx -> bg

		if (bg) {
			mx <- ar
		}
	}
}

a:int64 = [1, 8, 6, 2, 5, 4, 8, 3, 7]
r = max_area(a)  # = 等价于 <-
print(r)
