# 053: Maximum Subarray — Kadane 算法
# 算法: 动态规划 O(n)，cur = max(x, cur+x)
# 来源: LeetCode #53
# 期望输出:
#   6
def max_subarray() -> () {
	a <- [-2, 1, -3, 4, -1, 2, 1, -5, 4]
	n = len(a)  # = 等价于 <-
	a[0] -> cur
	max <- a[0]
	i = 1  # = 等价于 <-
	while (i < n) {
		a[i] -> x
		curx <- cur + x
		take_x = x > curx  # = 等价于 <-

		if (take_x) {
			x -> cur
		} else {
			cur <- curx
		}

		bigger = cur > max  # = 等价于 <-

		if (bigger) {
			cur -> max
		}

		i <- i + 1
	}
	print(max)
}

max_subarray()
