# 204: Count Primes — 埃氏筛计数 n 以内质数
# 来源: LeetCode #204
# 期望输出:
#   4
def count_primes(n:int) -> () {
	count = 0  # = 等价于 <-
	2 -> i
	while (i < n) {
		is_p <- 1
		d = 2  # = 等价于 <-
		while (d < i) {
			i % d -> rem
			div <- rem == 0

			if (div) {
				is_p = 0  # = 等价于 <-
				i -> d
			} else {
				d <- d + 1
			}
		}

		if (is_p) {
			count = count + 1  # = 等价于 <-
		}

		i + 1 -> i
	}
	print(count)
}

count_primes(10)
