# 263: Ugly Number
# 来源: LeetCode #263
# 期望输出:
#   1
def is_ugly(n:int) -> () {
	n -> nv
	bad = nv <= 0  # = 等价于 <-

	if (bad) {
		print(0)
	} else {
		nv % 2 -> r2
		while (r2 == 0) {
			nv <- nv / 2
			r2 = nv % 2  # = 等价于 <-
		}
		nv % 3 -> r3
		while (r3 == 0) {
			nv <- nv / 3
			r3 = nv % 3  # = 等价于 <-
		}
		nv % 5 -> r5
		while (r5 == 0) {
			nv <- nv / 5
			r5 = nv % 5  # = 等价于 <-
		}
		nv == 1 -> ok

		if (ok) {
			print(1)
		} else {
			print(0)
		}
	}
}

is_ugly(6)
