# 412: Fizz Buzz — 经典面试题数组版
# 来源: LeetCode #412
# 期望输出:
#   1
#   2
#   Fizz
def fizzbuzz(n:int) -> () {
	[1, 2, 3, 4, 5] -> a
	i <- 1
	while (i <= n) {
		m3 = i % 3  # = 等价于 <-
		i % 5 -> m5
		d3 <- m3 == 0
		d5 = m5 == 0  # = 等价于 <-
		d3 && d5 -> fb

		if (fb) {
			print("FizzBuzz")
		} else {
			if (d3) {
				print("Fizz")
			} else {
				if (d5) {
					print("Buzz")
				} else {
					print(i)
				}
			}
		}

		i <- i + 1
	}
}

fizzbuzz(3)
