# fizzbuzz: FizzBuzz 1-15（else if 多路分支）
# 期望输出:
#   1
#   Fizz
#   Buzz
#   FizzBuzz
def fizzbuzz(N:int64) -> () {
	i = 1  # = 等价于 <-
	while (i <= N) {
		i % 3 -> m3
		m5 <- i % 5
		d3 = m3 == 0  # = 等价于 <-
		m5 == 0 -> d5
		fb <- d3 && d5

		if (fb) {
			print("FizzBuzz")
		} else {
			if (d3) {
				print("Fizz")
			} else {
				if (d5) {
					print("Buzz")
				} else {
					print(i)
				}
			}
		}

		i = i + 1  # = 等价于 <-
	}
}

def main() -> () {
	fizzbuzz(15)
}

main()
