name: ci
on: [push, pull_request, repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载 ABI 依赖
        env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        run: ./ci/deps.sh
      - name: 构建
        run: make runtime runtime-rs layout
      - name: 测试
        env: { KVSPACE: "shm:///tmp/kvlang_ci" }
        run: python3 tutorial/test.py
