name: ci
on: [push, pull_request, repository_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 下载 ABI 依赖
        env: { GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}" }
        run: ./ci/deps.sh
      - name: 构建
        env: { KVSPACE_BACKEND_PATH: /usr/lib/kvspace }
        run: make shm
      - name: rwir 合同测试
        env: { KVSPACE_BACKEND_PATH: /usr/lib/kvspace }
        run: make test-rwir
      - name: 测试
        env:
          KVSPACE: "shm:///tmp/kvlang_ci"
          KVSPACE_BACKEND_PATH: /usr/lib/kvspace
        run: python3 tutorial/test.py
